### ISSUE TITLE
Add Full-Body Set option to giude

### ISSUE THREAD

**Issue by BakaJzon** [SlimeVR/SlimeVR-Docs-Site#116]
[Components guide](https://docs.slimevr.dev/diy/components-guide.html) doesn't include Full-Body Set (10 IMUs). I feel confused whether this set is available.
Could you please add Full-Body Set option to guide?

**Comment by Eirenliel** [comment]
You can build any set you want, that's for DIY :P

**Comment by Smeltie** [comment]
> [Components guide](https://docs.slimevr.dev/diy/components-guide.html) doesn't include Full-Body Set (10 IMUs). I feel confused whether this set is available. Could you please add Full-Body Set option to guide?

The beauty of DIY is that it is theoretically scalable to as many trackers as you can physically build yourself.
So all you have to do to build a 10pcs set is order components for 10 trackers.
the guide currently should be a good indication what you need for individual trackers.
Scaling this up or down doesn't change anything specifically except the user needing to order more of X parts.

Will be closing this issue as this is not a required change to the docs
