### ISSUE TITLE
IMU Comparation details?

### ISSUE THREAD

**Issue by fred913** [SlimeVR/SlimeVR-Docs-Site#183]
Well, as what I said in #177 , while I highly doubt why MPU+QMC5883L is considered worse than MPU6500, I'm not sure how the ratings of the IMUs are set. May there be detailed comparation between all the IMUs? E.g. a table

**Comment by calliePepper** [comment]
I would have to double-check with the people involved, but I think the comparison table is put together based on survey results of them in use?

**Comment by Smeltie** [comment]
the results are based on the average score given by people in the community through a survey.
