### ISSUE TITLE
Few broken hyperlinks

### ISSUE THREAD

**Issue by Spazzwanjunk** [SlimeVR/SlimeVR-Docs-Site#70]
https://docs.slimevr.dev/diy/diy-trackers-guide.html
![image](https://user-images.githubusercontent.com/98095416/151355197-191e817b-d849-495f-bdef-3ab14f1e2b25.png)

and https://docs.slimevr.dev/
![image](https://user-images.githubusercontent.com/98095416/151355139-9f3e8dad-5ab0-4305-a1db-a41b45ee049b.png)

are linking to https://docs.slimevr.dev/firmware/upload-firmware-guide.md instead of https://docs.slimevr.dev/firmware/upload-firmware-guide.html

**Comment by Spazzwanjunk** [comment]
here too:
![image](https://user-images.githubusercontent.com/98095416/151355804-a1e5f9e2-f0a0-4a2f-aca7-0fb3a01eb2a8.png)
https://docs.slimevr.dev/slimevr101.html

**Comment by Eirenliel** [comment]
Resolved in #71 if I understand correctly.
