### ISSUE TITLE
Optional components

### ISSUE THREAD

**Issue by Spazzwanjunk** [SlimeVR/SlimeVR-Docs-Site#76]
Additional section in the components guide should be considered, as people have ordered all the parts from this page and not noticed the optional pieces on the schematics. Suggested formatting below:

Optional components:
There are several components that can be added when building a tracker that allow for additional features. A 'Battery sense' resistor can be added to allow the server to determine battery level, while a pair of diodes can be added to allow the tracker to be used while charging and as an added safety measure against accidental damage due to charging while powered on. While both these additions are extremely low cost, they are considered optional and can increase the complexity of the schematics.
Recommended resistor is: 180k Ohm 1/4W Metal Film Resistor
Recommended diodes are: 1N5817 SCHOTTKY Diode

**Comment by Smeltie** [comment]
It seems this has since already been implemented into the Docs.
Going to close this issue unless further changes have to be made.
